import java.util.ArrayList;
import java.math.BigInteger;
/* https://projecteuler.net/problem=29 Distinct Powers
How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
*/
public class problem29 {
    public static void main(String[] args) {
        System.out.println(countDistinctPowers(2,100));
    }

    public static int countDistinctPowers(int lower, int upper){
        ArrayList<BigInteger> list = new ArrayList<BigInteger>();
        for(int a = lower; a <= upper; a++) {
            for(int b = lower; b <= upper; b++) {
                BigInteger base = new BigInteger(Integer.toString(a));
                BigInteger power = base.pow(b);
                if(!list.contains(power)) { list.add(power); }
            }
        }
        return list.size();
    }   
}